name: Sync to S3
description: "Brings the website on S3 up-to-date"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up database & backend
        run:  docker compose up --build

      - name: Change directory & Install dependencies
        run:  cd frontend && npm install

      - name: Build
        run:  rm -rf dist && ng build -- --configuration production
        
      - name: Configure AWS credentials for authorization
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-north-1'

      - name: Deploy HTML files to S3
        run: |
          aws s3 sync ./dist/frontend/browser s3://bulwriter \
            --delete \
            --exclude "index.html" \
            --cache-control "max-age=31536000, immutable"
      
      - name: Upload index.html
        run: |
          aws s3 cp ./dist/frontend/browser/index.html s3://bulwriter/index.html \
            --cache-control "no-store, no-cache, must-revalidate" \
            --content-type "text/html"
            
          # aws s3 cp ./dist/frontend/browser/index.html s3://bulwriter/ --cache-control "no-store, no-cache, must-revalidate" --content-type "text/html"
          # aws s3 cp ./dist/frontend/browser s3://bulwriter/ --recursive --exclude "*" --include "*.css" --cache-control "max-age=31536000, immutable" --content-type "text/css"
          # aws s3 sync ./dist/frontend/browser s3://bulwriter/ --exclude "index.html" --exclude "*.css" --cache-control "max-age=31536000, immutable" --delete
